#!/usr/bin/env bash

# Switches between ARM64 (native M1 Mac tools) and x86-64 Golang tools.

ARCH=$(arch)

export GOVERSION=${GOVERSION:-1.18.10}

case "$ARCH" in
    arm64)
        export GOPATH=$HOME/Code/go/$GOVERSION/arm64
        ;;
    i386)
        export GOPATH=$HOME/Code/go/$GOVERSION/i386
        ;;
    *)
        echo "Invalid architecture (valid options: arm64, i386)" 1>&2
        exit 1
        ;;
esac

export PATH="$GOPATH/bin:$PATH"
echo $PATH
export PKG_CONFIG_PATH=$PKG_CONFIG_PATH:/usr/local/lib/pkgconfig
